name: linux

on:
  push:
    paths:
      - 'linux/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Get Linux
      id: ronaronatangtang
      run: |
        linuxHash=$(git rev-parse HEAD:linux)
        wget -O myLinux https://github.com/BaeRoNuI/linux/archive/${linuxHash}.zip
      
    - name: Unzip Linux
      run: unzip myLinux
      
    - name: Install dephs
      run: ./install-deps.sh
      
    - name: Build Linux with tinyconfig
      run: |
        linuxHash=$(git rev-parse HEAD:linux)
        ./build-linux.sh linux-${linuxHash} tinyconfig