name: CSI2115 Linux kernel

on:
  push:
    paths:
      - 'linux/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Tinyconfig
        run: ./install-deps.sh;linux_hash=$(git rev-parse HEAD:linux);./build-linux.sh ./linux-$linux_hash tinyconfig;
