name: CSI2115 Linux kernel

on:
  push:
  path:
    - 'linux/*'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: compile the linux
      shell: bash
      run: |
        ./build-linux.sh ./linux tinyconfig